name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y gnu-efi build-essential
        
      - name: Build EFI driver
        run: |
          cd driver
          make
          ls -R
          mkdir -p ../build/
          mv ./ ../build/
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ github.event.repository.name }}
          path: build/*
