name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [x86, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y gnu-efi build-essential
        
      - name: Build EFI driver
        run: |
          cd driver
          make clean
          make ARCH=${{ matrix.arch }}  # Adjust as needed for architecture-specific builds
          mkdir -p ../build-${{ matrix.arch }}/Release
          mv output_files_here ../build-${{ matrix.arch }}/Release  # Update this as needed

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.arch }}
          path: build-${{ matrix.arch }}/Release/*
