name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Build EFI driver
        run: |
          cd driver
          sudo apt install gnu-efi build-essential
          make clean
          make

      - name: Artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{github.event.repository.name}}-${{matrix.arch}}
          path: build-${{matrix.arch}}/Release/*
