name: Build EFI Driver

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential gcc-aarch64-linux-gnu gcc-x86-64-linux-gnu

    - name: Build with Makefile
      run: make

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: efi-driver
        path: ./output/
